FROM golang:1.24-alpine AS base
RUN apk add --no-cache ca-certificates tzdata git make
WORKDIR /app

FROM base AS development
RUN go install github.com/air-verse/air@latest
CMD ["air"]

FROM base AS builder
COPY go.work go.work.sum ./
COPY packages/ ./packages/
WORKDIR /app/services
ARG SERVICE_PATH
COPY services/$SERVICE_PATH ./$SERVICE_PATH
RUN go build -o /app/service ./$SERVICE_PATH/cmd/server/

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /app/service /service
ENTRYPOINT ["/service"]
