name: mobile
description: "Horizon mobile app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  http: ^1.6.0
  google_fonts: ^8.1.0
  shared_preferences: ^2.5.5
  percent_indicator: ^4.2.5
  file_picker: ^8.1.7
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/camel.png
    - assets/flower-pot-1.png
    - assets/flower-pot.png
    - assets/leaf.png

